version: "3.4"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
      #target: development
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000"
    networks:
      - front
      - back
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=gelisimatolyesiotizm.com,www.gelisimatolyesiotizm.com
      - LETSENCRYPT_HOST=gelisimatolyesiotizm.com,www.gelisimatolyesiotizm.com
      - LETSENCRYPT_EMAIL=mehmet@narapp.com   
    command: npm run dev


networks:
  front:
    external:
      name: front
  back:
    external:
      name: back  